# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Nome:')),
                ('sobre_nome', models.CharField(max_length=20, verbose_name='Sobre nome:')),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10, verbose_name='Sexo:')),
                ('facebook', models.URLField(verbose_name='Facebook:')),
                ('email', models.EmailField(max_length=254, verbose_name='Digite seu E-mail:')),
                ('favorito', models.BooleanField(verbose_name='Favorito:')),
            ],
        ),
    ]
