# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 22:56
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=builtins.id, help_text='Preenchido automaticamente, não editar.', max_length=200, unique=True, verbose_name='Slug / URL'),
            preserve_default=False,
        ),
    ]
