# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_auto_20160908_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
